export const ENGRAVINGS = {
    'Презрение к слабым': '/achieve/achieve_04_30.png',
    'Стремительность': '/buff/buff_65.png',
    'Час жатвы': '/buff/buff_74.png',
    'Бравада': '/buff/buff_105.png',
    'Титаноборец': '/buff/buff_71.png',
    'Мастер подготовки': '/achieve/achieve_06_14.png',
    'Несокрушимый боец': '/buff/buff_44.png',
    'Собиратель душ': '/buff/buff_18.png',
    'Обман смерти': '/buff/buff_162.png',
    'Моргенштерн': '/achieve/achieve_03_40.png',
    'Иссечение': '/buff/buff_168.png',
    'Источник маны': '/buff/buff_122.png',
    'Астральное тело': '/buff/buff_166.png',
    'Молниеносные рефлексы': '/buff/buff_10.png',
    'Неутомимость': '/buff/buff_66.png',
    'Тактическое превосходство': '/buff/buff_83.png',
    'Разрушитель щитов': '/buff/buff_89.png',
    'Стальные нервы': '/buff/buff_147.png',
    'Божественная защита': '/buff/buff_229.png',
    'Тяжелая броня': '/buff/buff_46.png',
    'Гренадер': '/buff/buff_121.png',
    'Отражающий барьер': '/buff/buff_239.png',
    'Темный пакт': '/buff/buff_29.png',
    'Засада': '/achieve/achieve_08_62.png',
    'Беспощадность': '/buff/buff_94.png',
    'Грозовая буря': '/buff/buff_191.png',
    'Голем': '/buff/buff_237.png',
    'Победная эйфория': '/buff/buff_136.png',
    'Бесшумный убийца': '/buff/buff_148.png',
    'Безмятежный дух': '/buff/buff_63.png',
    'Лучшая защита': '/buff/buff_170.png',
    'Неутомимый натиск': '/buff/buff_210.png',
    'Новый рассвет': '/buff/buff_113.png',
    'Гильотина': '/ability/ability_224.png',
    'Карающая длань': '/ability/ability_231.png',
    'Обманный маневр': '/ability/ability_232.png',
    'Побоище': '/ability/ability_233.png',
    'ПАНИКА': '/ability/ability_234.png',
    'Адреналин': '/ability/ability_235.png',
    'Скоротечная расправа': '/ability/ability_236.png',
    'Заступник': '/ability/ability_237.png',
    'Скорая помощь': '/ability/ability_238.png',
    'Скальпель': '/ability/ability_239.png',
    'Тёмное безрассудство': '/ability/ability_270.png',
    'Безрассудство': '/ability/ability_269.png',
    'Универсал': '/ability/ability_242.png',
    'Пистолеты и пули': '/buff/buff_600.png',
    'Кибер-солдат': '/ability/ability_271.png',
    'Бомбардировка': '/gl_skill/gl_skill_01_26.png',
    'Рвение защитника': '/ability/ability_266.png',
    'Герой-одиночка': '/ability/ability_267.png',
    'Четвертая чакра': '/buff/buff_238.png',
    'Перерождение': '/ability/ability_25.png',
    'Избранный путь': '/achieve/achieve_07_22.png',
    'Ликующий дух': '/buff/buff_177.png',
    'Кантата доблести': '/ability/ability_275.png',
    'Экстаз': '/ability/ability_276.png',
    'Гравитационное сжатие': '/achieve/achieve_08_49.png',
    'Стабильная гравитация': '/ability/ability_268.png',
    'Мудрость Энвиссы': '/buff/buff_78.png',
    'Чародейская гениальность': '/ability/ability_274.png',
    'Императрица': '/ability/ability_272.png',
    'Император': '/ability/ability_273.png',
    'Медитация': '/buff/buff_235.png',
    'Воплощение Силы': '/ability/ability_45.png',
    'Вторая модель': '/ability/ability_47.png',
    'Последний полет': '/buff/buff_245.png',
    'Превосходство светил': '/ability/ability_207.png',
    'Полнолуние': '/ability/ability_208.png',
    'Остаточная энергия': '/ability/ability_209.png',
    'Твердая воля': '/ability/ability_210.png',
    'Абсолютный контроль': '/ability/ability_211.png',
    'Темная сторона': '/ability/ability_212.png',
    'Мастер-фехтовальщик': '/ability/ability_214.png',
    'Исцеляющая вера': '/ability/ability_215.png',
    'Технология Ардетайна': '/ability/ability_216.png',
    'Наследие «Генезиса»': '/ability/ability_217.png',
    'Жажда': '/ability/ability_222.png',
    'Голос луны': '/ability/ability_223.png',
    'Миротворец': '/ability/ability_225.png',
    'Отстрел': '/ability/ability_228.png',
    'Ва-банк': '/ability/ability_230.png',
    'Баланс элементов': '/ability/ability_229.png',
    'Обострённые чувства': '/ability/ability_240.png',
    'Осознанный диссонанс': '/ability/ability_241.png',
    'Круговорот светил': '/ability/ability_248.png',
    'Весенний рассвет': '/ability/ability_249.png',
    'Повелитель бури': '/ability/ability_258.png',
    'Сезон дождей': '/ability/ability_259.png',
    'Хищница': '/ability/ability_260.png',
    'Воля палача': '/ability/ability_261.png',
    'Бледная луна': '/ability/ability_263.png',
    'Узы судьбы': '/ability/ability_264.png'
};